// ─────────────────────────────────────────────────────────────────────────────
// GÉNÉRÉ — ne pas éditer à la main.
//   1. `npx tsx scripts/i18n-extract-apps.mts`   (extrait les chaînes FR affichées)
//   2. traduire les lots
//   3. `node scripts/i18n-build-app-dict.mjs`     (reconstruit ce fichier)
//
// Texte AFFICHÉ des 10 apps phares, FR → EN. Consommé par lib/app-html-i18n.ts.
// Ne contient QUE du texte humain : aucune clé d'entité, aucun nom de colonne,
// aucune valeur d'enum stockée (les traduire casserait données, filtres, agents).
// ─────────────────────────────────────────────────────────────────────────────

export const APP_STRINGS_EN: Record<string, string> = {
  "Dictez un ou plusieurs devis : « Devis pour M. Martin, rénovation salle de bain : dépose carrelage 45 m² à 18 €, pose à 42 €, un WC suspendu à 620 € »": "Dictate one or more quotes: 'Quote for Mr. Martin, bathroom renovation: tile removal 45 m² at 18 €, laying at 42 €, one wall-hung toilet at 620 €'",
  "Facturez un chantier et pointez des heures : la rentabilité réelle (facturé − coûts) s'affichera ici. Ou ajoutez un budget prévu à un chantier.": "Invoice a job site and track hours: real profitability (invoiced − costs) will show up here. Or add a planned budget to a job site.",
  "Bonjour,\n\nDans le cadre de nos obligations, merci de bien vouloir nous transmettre votre attestation d'assurance décennale à jour": "Hello,\n\nAs part of our compliance requirements, please send us your up-to-date 10-year liability insurance certificate",
  "Créez une facture : votre cash bloqué, votre DSO et vos courbes d'encaissement s'afficheront ici, en direct.": "Create an invoice: your locked-up cash, your DSO and your collection curves will show up here, live.",
  "Vérifiez le client et les montants, puis enregistrez. Rien n'est écrit tant que vous n'avez pas validé.": "Check the client and the amounts, then save. Nothing is written until you confirm.",
  "Vos encaissements alimenteront votre courbe de trésorerie dès votre première facture payée.": "Your collections will feed your cash flow curve as soon as your first invoice is paid.",
  "Créez votre première tâche et glissez-la d'une colonne à l'autre au fil de l'avancement.": "Create your first task and drag it from one column to the next as work progresses.",
  ". Restant à votre disposition pour en discuter et avancer ensemble.\n\nBien cordialement,": ". Happy to discuss and move forward together.\n\nBest regards,",
  "Nous vous remercions de bien vouloir procéder au règlement dans les meilleurs délais.": "We kindly ask you to make payment as soon as possible.",
  "Ajoutez vos contrats d'entretien pour suivre le récurrent et les prochaines visites.": "Add your servicing contracts to track recurring revenue and upcoming visits.",
  "Ajoutez vos prestations et prix : ils seront insérables en un clic dans vos devis.": "Add your services and prices: you can insert them into your quotes in one click.",
  "Merci de nous confirmer la disponibilité et le délai de livraison.\n\nCordialement,": "Please confirm availability and delivery lead time.\n\nBest regards,",
  "Renseignez l'assurance décennale de vos sous-traitants pour suivre les échéances.": "Enter your subcontractors' 10-year liability insurance to track due dates.",
  "Bonjour,\n\nMerci de nous préparer la commande de réapprovisionnement suivante :": "Hello,\n\nPlease prepare the following restock order for us:",
  "Personne n'est planifié aujourd'hui. Affectez votre équipe depuis le planning.": "Nobody is scheduled today. Assign your team from the schedule.",
  "Créez votre premier chantier pour voir votre tableau de bord prendre vie.": "Create your first job site to bring your dashboard to life.",
  "Planifiez une prochaine action sur vos opportunités pour ne rien oublier.": "Schedule a next action on your opportunities so nothing slips.",
  "Dictez votre premier devis ou créez-le à la main : il se retrouvera ici.": "Dictate your first quote or create it by hand: it will show up here.",
  "Rien d'urgent : aucun retard ni échéance proche. Tout est sous contrôle.": "Nothing urgent: nothing overdue, no due dates coming up. All under control.",
  "Ajoutez les membres de votre équipe pour les affecter à vos chantiers.": "Add your team members to assign them to your job sites.",
  "ÉTAT — semaine prête, non planifiés, et surtout QUI ne recevra pas son": "STATUS — week ready, unscheduled, and above all WHO will not get their",
  "Ajoutez un budget prévu à un chantier pour comparer le prévu au réel.": "Add a planned budget to a job site to compare planned vs. actual.",
  "entreprise) et le lien de consultation sont produits côté serveur. */": "company) and the view link are generated server-side. */",
  "Supprimer ce fournisseur ? Les articles liés ne seront pas supprimés.": "Delete this supplier? Linked items will not be deleted.",
  "Toutes vos interventions sont à jour. Planifiez la prochaine visite.": "All your jobs are up to date. Schedule the next visit.",
  "Ajoutez des équipiers pour construire votre planning de la semaine.": "Add team members to build your schedule for the week.",
  "Ajoutez les membres de votre équipe pour leur attribuer des tâches.": "Add your team members to assign them tasks.",
  "Créez des tâches pour suivre la charge de l'équipe et l'avancement.": "Create tasks to track team workload and progress.",
  "impayé. La facture PART AVEC : un client relancé sans la pièce doit": "unpaid. The invoice GOES WITH IT: a client chased without the document has to",
  "Aucun devis en attente de réponse. Rien à relancer pour l'instant.": "No quotes awaiting a reply. Nothing to chase up right now.",
  "y .7s cubic-bezier(.2,.8,.2,1),height .7s cubic-bezier(.2,.8,.2,1)": "y .7s cubic-bezier(.2,.8,.2,1),height .7s cubic-bezier(.2,.8,.2,1)",
  "Supprimer ce client ? Ses opportunités ne seront pas supprimées.": "Delete this client? Their opportunities will not be deleted.",
  "Recensez les chaudières, PAC, VMC… installées chez vos clients.": "List the boilers, heat pumps, ventilation units… installed at your clients'.",
  "Ajoutez vos pistes commerciales pour piloter votre pipeline.": "Add your sales leads to manage your pipeline.",
  "app ne rédige PLUS le corps du mail : elle désigne la FICHE.": "app NO LONGER writes the email body: it points to the RECORD.",
  "Créez votre première facture pour suivre vos encaissements.": "Create your first invoice to track your collections.",
  "Ajoutez vos matériaux et fournitures pour suivre le stock.": "Add your materials and supplies to track stock.",
  "Aucune assurance décennale à renouveler dans les 30 jours.": "No 10-year liability insurance to renew in the next 30 days.",
  "Aucune ligne détaillée. Modifiez le devis pour en ajouter.": "No line items. Edit the quote to add some.",
  "Tous vos articles sont au-dessus de leur seuil d'alerte.": "All your items are above their alert threshold.",
  "Ajoutez les membres de votre équipe pour les planifier.": "Add your team members to schedule them.",
  "Ajoutez votre matériel et affectez-le à vos chantiers.": "Add your equipment and assign it to your job sites.",
  "Aucune attestation d'assurance décennale enregistrée.": "No 10-year liability insurance certificate on file.",
  "Devis valable 30 jours. Acompte de 30% à la commande.": "Quote valid for 30 days. 30% deposit on order.",
  "Les heures pointées se répartissent ici par chantier.": "Tracked hours are broken down here by job site.",
  "Créez la facture depuis ce devis, sans rien retaper.": "Create the invoice from this quote, without retyping anything.",
  "Vérifiez votre connexion puis rouvrez l'application.": "Check your connection then reopen the app.",
  "Ajoutez l'email du client pour lui envoyer le devis": "Add the client's email to send them the quote",
  "Ajoutez vos clients pour les rattacher à vos devis.": "Add your clients to link them to your quotes.",
  "Travaux réalisés, pièces changées, recommandations…": "Work done, parts replaced, recommendations…",
  "Ajoutez vos négoces et fournisseurs de matériaux.": "Add your merchants and material suppliers.",
  "Rechercher un équipement, un client, une marque…": "Search equipment, a client, a brand…",
  "Aucune ligne. Ajoutez une prestation ci-dessus.": "No lines. Add a service above.",
  "Parlez, Biltia le rédige et calcule les totaux.": "Just talk, Biltia writes it and computes the totals.",
  "Rechercher un partenaire, un métier, une ville…": "Search a partner, a trade, a city…",
  "Biltia rédige vos devis et calcule les totaux.": "Biltia writes your quotes and computes the totals.",
  "Dictée non comprise, réessayez plus clairement": "Dictation not understood, try again more clearly",
  "» — sera créé si vous n'en choisissez pas un.": "' — will be created if you don't pick one.",
  "Ajoutez votre premier dépannage ou entretien.": "Add your first emergency repair or servicing.",
  "Aucun encaissement enregistré pour l'instant.": "No collections recorded yet.",
  "Les interventions clôturées apparaîtront ici.": "Closed jobs will show up here.",
  "Rechercher un chantier, un client, une ville…": "Search a job site, a client, a city…",
  "Rechercher un numéro, un client, un chantier…": "Search a number, a client, a job site…",
  "Ajoutez votre équipe pour suivre les heures.": "Add your team to track hours.",
  "Aucune tâche en retard. L'équipe est à jour.": "No overdue tasks. The team is up to date.",
  "✓ Toute l'équipe est planifiée et joignable": "✓ The whole team is scheduled and reachable",
  "Ajoutez vos sous-traitants et fournisseurs.": "Add your subcontractors and suppliers.",
  "Ajoutez l'email du client pour le relancer": "Add the client's email to chase them up",
  "Autorisez le micro pour dicter votre devis": "Allow the mic to dictate your quote",
  "Bonjour,\n\nJe reviens vers vous au sujet de": "Hello,\n\nI'm getting back to you regarding",
  "Ce fournisseur n'a pas d'email — l'ajouter": "This supplier has no email — add one",
  "Recommandation, appel d'offres, site web…": "Referral, tender, website…",
  "Supprimer cette prestation du catalogue ?": "Delete this service from the price list?",
  "Attestation d'assurance décennale à jour": "Up-to-date 10-year liability insurance certificate",
  "Nous vous en souhaitons bonne réception.": "We trust you will find everything in order.",
  "Pointez le temps passé par votre équipe.": "Track the time your team spends.",
  "Supprimer définitivement cette facture ?": "Permanently delete this invoice?",
  "Aucun chantier en cours pour le moment.": "No job sites in progress right now.",
  "de retard. Votre recouvrement est sain.": "overdue. Your collections are healthy.",
  "on lui réclame. Le PDF (logo + couleurs": "we're chasing them for. The PDF (logo + colors",
  "sans email — n'auront pas leur planning": "with no email — won't get their schedule",
  "Associer un fournisseur à ces articles": "Link a supplier to these items",
  "Remarques (non visibles par le client)": "Notes (not visible to the client)",
  "Supprimer définitivement le chantier «": "Permanently delete job site '",
  "Symptôme, matériel concerné, contexte…": "Symptom, equipment involved, context…",
  "Micro non disponible sur cet appareil": "Mic not available on this device",
  "Rechercher un article, une référence…": "Search an item, a reference…",
  "Rechercher un fournisseur, une ville…": "Search a supplier, a city…",
  "Sauf erreur de notre part, la facture": "Unless we are mistaken, invoice",
  "Aucun encours client à recouvrer. 👌": "No client receivables to collect. 👌",
  "Aucun résultat pour cette recherche.": "No results for this search.",
  "Dictez ou créez votre premier devis.": "Dictate or create your first quote.",
  "(la précédente arrive à échéance le": "(the previous one expires on",
  "Assurance décennale (n° / assureur)": "10-year liability insurance (no. / insurer)",
  "Supprimer définitivement le devis «": "Permanently delete quote '",
  "Aucun devis reconnu dans la dictée": "No quote recognized in the dictation",
  "Aucune opportunité pour ce client.": "No opportunities for this client.",
  "Changez de filtre ou de recherche.": "Change the filter or the search.",
  "Matériaux, électricité, plomberie…": "Materials, electrical, plumbing…",
  "Rechercher une tâche, un chantier…": "Search a task, a job site…",
  "Retirer cet équipier de la liste ?": "Remove this team member from the list?",
  "Ajoutez vos clients et prospects.": "Add your clients and leads.",
  "Conditions de paiement, validité…": "Payment terms, validity…",
  "Connexion au workspace impossible": "Can't connect to the workspace",
  "Rechercher un client, une ville…": "Search a client, a city…",
  "Réutilisable dans tous vos devis": "Reusable across all your quotes",
  "Ajoutez au moins une prestation": "Add at least one service",
  "Clients qui bloquent votre cash": "Clients tying up your cash",
  "Commande de réapprovisionnement": "Restock order",
  "Rentabilité réelle par chantier": "Real profitability by job site",
  "Toute l'équipe est affectée. 👍": "The whole team is assigned. 👍",
  "Assurance décennale · échéance": "10-year liability insurance · due date",
  "Aucun email pour ce partenaire": "No email for this partner",
  "Aucun résultat pour ce filtre.": "No results for this filter.",
  "Nature des travaux, remarques…": "Type of work, notes…",
  "Rien à analyser pour l'instant": "Nothing to analyze right now",
  "Supprimer cette intervention ?": "Delete this job?",
  "Aucun chantier pour l'instant": "No job sites yet",
  "Conditions, matériel couvert…": "Terms, equipment covered…",
  "Conditions, remises, contact…": "Terms, discounts, contact…",
  "Créez votre premier chantier.": "Create your first job site.",
  "Emplacement, conditionnement…": "Location, packaging…",
  "en cours · taux de conversion": "in progress · conversion rate",
  "Lecture de l'audio impossible": "Can't read the audio",
  "SCI Méditerranée, M. Vasseur…": "Oakwood Properties, Mr. Smith…",
  "Supprimer cette opportunité ?": "Delete this opportunity?",
  "Valeur du stock par catégorie": "Stock value by category",
  "Aucun chantier ne correspond": "No job site matches",
  "Aucune facture ne correspond": "No invoice matches",
  "Aucune intervention terminée": "No completed jobs",
  "Cash bloqué chez vos clients": "Cash tied up with your clients",
  "Désignation de la prestation": "Service description",
  "Parc installé chez le client": "Equipment installed at the client",
  "Préparation du devis en PDF…": "Preparing the quote PDF…",
  "Revenu récurrent (annualisé)": "Recurring revenue (annualized)",
  "Spécialité / corps de métier": "Specialty / trade",
  "Trésorerie encaissée (cumul)": "Cash collected (cumulative)",
  "— Fournisseur (optionnel) —": "— Supplier (optional) —",
  "— Intervenant (optionnel) —": "— Assignee (optional) —",
  "Aucun seuil d'alerte défini": "No alert threshold set",
  "Aucune opportunité en cours": "No open opportunities",
  "Enregistrement non supporté": "Recording not supported",
  "Extension R+2, villa neuve…": "Two-story extension, new villa…",
  "sont bloqués depuis plus de": "are tied up for more than",
  "Sous-traitance & conformité": "Subcontracting & compliance",
  "— à escalader en priorité.": "— to escalate first.",
  "— Équipement (optionnel) —": "— Equipment (optional) —",
  "Aucun devis pour l'instant": "No quotes yet",
  "Aucun email pour ce client": "No email for this client",
  "Aucune heure cette semaine": "No hours this week",
  "Budget engagé par chantier": "Committed budget by job site",
  "commanderSupplier(''+k+'')": "commanderSupplier(''+k+'')",
  "Dépannage, entretien, SAV…": "Emergency repair, servicing, after-sales…",
  "Détails, budget, décideur…": "Details, budget, decision-maker…",
  "Planifier une intervention": "Schedule a job",
  "Pour recevoir son planning": "To receive their schedule",
  "Sac de ciment CEM II 35kg…": "Bag of CEM II cement 35kg…",
  "stroke-dashoffset .9s ease": "stroke-dashoffset .9s ease",
  "Supprimer cet équipement ?": "Delete this equipment?",
  "Affaires gagnées par mois": "Deals won per month",
  "Aucun devis ne correspond": "No quote matches",
  "Aucune échéance planifiée": "No due date scheduled",
  "Aucune facture au-delà de": "No invoice more than",
  "Chef d'équipe, compagnon…": "Team leader, tradesperson…",
  "CRM — Pipeline commercial": "CRM — Sales pipeline",
  "email, plan, canal…) */ }": "email, plan, channel…) */ }",
  "Encaissement enregistré ·": "Collection recorded ·",
  "Enregistrement impossible": "Recording failed",
  "facturé − heures − achats": "invoiced − hours − purchases",
  "Historique, spécificités…": "History, specifics…",
  "M. Dupont / SCI Les Lilas": "Mr. Smith / Oakwood Properties",
  "Nom du chef de chantier :": "Site manager name:",
  "Pas encore d'encaissement": "No collection yet",
  "Pose carrelage sol collé…": "Glued floor tiling…",
  "Réponse attendue · expire": "Reply expected · expires",
  "stroke-dashoffset 1s ease": "stroke-dashoffset 1s ease",
  "Supprimer ce partenaire ?": "Delete this partner?",
  "+ Ajouter une prestation": "+ Add a service",
  "1A;border-left:3px solid": "1A;border-left:3px solid",
  "Analyse de votre dictée…": "Analyzing your dictation…",
  "Couverture, électricité…": "Roofing, electrical…",
  "en attente d'affectation": "awaiting assignment",
  "Gros œuvre, Électricité…": "Structural work, Electrical…",
  "Intervention enregistrée": "Job saved",
  "main d'œuvre + matériaux": "labor + materials",
  "Nacelle 12m, bétonnière…": "12m lift, cement mixer…",
  "Relancer, envoyer devis…": "Chase up, send quote…",
  "— Choisir un équipier —": "— Select a team member —",
  "+ Ajouter un partenaire": "+ Add a partner",
  "+ Nouvelle intervention": "+ New job",
  "➕ Autre nouveau client…": "➕ Other new client…",
  "Affectation enregistrée": "Assignment saved",
  "Assurances qui expirent": "Expiring insurance",
  "Aucune tâche active. 👌": "No active tasks. 👌",
  "Coordonnées à compléter": "Contact details to complete",
  "Création de la facture…": "Creating invoice…",
  "Devis valable 30 jours.": "Quote valid for 30 days.",
  "Fournisseur introuvable": "Supplier not found",
  "Interventions à traiter": "Jobs to handle",
  "Interventions clôturées": "Closed jobs",
  "Modifier l'intervention": "Edit job",
  "Modifier le fournisseur": "Edit supplier",
  "Nom du nouveau client :": "New client name:",
  "Opportunité enregistrée": "Opportunity saved",
  "Rénovation Villa Martin": "Villa Martin Renovation",
  "Rien à réapprovisionner": "Nothing to restock",
  "Rien n'a été enregistré": "Nothing was saved",
  "Supprimer ce matériel ?": "Delete this equipment?",
  "Supprimer ce pointage ?": "Delete this time entry?",
  "Supprimer cet article ?": "Delete this item?",
  "Supprimer cette tâche ?": "Delete this task?",
  "Vérifier le devis dicté": "Check the dictated quote",
  "— Aucun (jour libre) —": "— None (day off) —",
  "+ Nouvelle opportunité": "+ New opportunity",
  "➕ Depuis le catalogue…": "➕ From price list…",
  "➕ Nouveau fournisseur…": "➕ New supplier…",
  "À relancer aujourd'hui": "Chase up today",
  "À relancer en priorité": "Chase up first",
  "Ajouter une prestation": "Add a service",
  "Aucun devis enregistré": "No quotes saved",
  "Contexte, préférences…": "Context, preferences…",
  "Couler la dalle du R+2": "Pour the 2nd floor slab",
  "Création de l'acompte…": "Creating deposit…",
  "entreprise (Réglages →": "company (Settings →",
  "Finance & recouvrement": "Finance & collections",
  "Fournisseur enregistré": "Supplier saved",
  "Indiquez un montant HT": "Enter an amount excl. VAT",
  "Intervention supprimée": "Job deleted",
  "Intitulé du chantier :": "Job site name:",
  "Mise à jour impossible": "Update failed",
  "Modifier l'affectation": "Edit assignment",
  "Modifier l'opportunité": "Edit opportunity",
  "Modifier la prestation": "Edit service",
  "Modifier le partenaire": "Edit partner",
  "Montant encaissé (€) :": "Amount collected (€):",
  "Nom / raison sociale *": "Name / legal name *",
  "Occupation de l'équipe": "Team workload",
  "Où en est votre argent": "Where your money stands",
  "Planifier un entretien": "Schedule servicing",
  "Point P, Rexel, Cedeo…": "Point P, Rexel, Cedeo…",
  "Précisions, consignes…": "Details, instructions…",
  "Prestation enregistrée": "Service saved",
  "Rapport d'intervention": "Job report",
  "Relancer l'attestation": "Chase up certificate",
  "Remarques, conditions…": "Notes, terms…",
  "Retirer cet équipier ?": "Remove this team member?",
  "Suppression impossible": "Delete failed",
  "Supprimer ce contrat ?": "Delete this contract?",
  "un agent « tourne » (l": "an agent 'runs' (the",
  "— Choisir un client —": "— Select a client —",
  ") reste à régler pour": ") left to pay for",
  "+ Affecter une équipe": "+ Assign a team",
  "+ Ajouter du matériel": "+ Add equipment",
  "+ Ajouter un équipier": "+ Add a team member",
  "+ Nouveau fournisseur": "+ New supplier",
  "+ Nouvelle prestation": "+ New service",
  "À traiter en priorité": "Handle first",
  "Aucun chantier dirigé": "No job site managed",
  "background:var(--vio)": "background:var(--vio)",
  "Budgets & rentabilité": "Budgets & profitability",
  "de votre cash bloqué.": "of your cash tied up.",
  "En attente de réponse": "Awaiting reply",
  "Encaissements récents": "Recent collections",
  "Engagé / coûts (€ HT)": "Committed / costs (€ excl. VAT)",
  "envoi a besoin. ── */": "sending needs. ── */",
  "Équipement enregistré": "Equipment saved",
  "Glissez une tâche ici": "Drag a task here",
  "Intervention démarrée": "Job started",
  "Intervention terminée": "Job completed",
  "Matériau / fourniture": "Material / supply",
  "Matin, tâche précise…": "Morning, specific task…",
  "Modifier l'équipement": "Edit equipment",
  "Nouvelle intervention": "New job",
  "Opportunité supprimée": "Opportunity deleted",
  "Partenaire enregistré": "Partner saved",
  "Semaine à planifier —": "Week to schedule —",
  "Supprimer ce client ?": "Delete this client?",
  "Toiture Pro, Point P…": "Toiture Pro, Point P…",
  "Type d'intervention *": "Job type *",
  "Validation impossible": "Validation failed",
  "— relancez le client": "— chase up the client",
  "+ Pointer des heures": "+ Log hours",
  "8 dernières semaines": "Last 8 weeks",
  "Aucune heure ce jour": "No hours this day",
  "background:var(--cy)": "background:var(--cy)",
  "background:var(--em)": "background:var(--em)",
  "background:var(--gd)": "background:var(--gd)",
  "background:var(--rz)": "background:var(--rz)",
  "background:var(--sl)": "background:var(--sl)",
  "Carreleur, plombier…": "Tiler, plumber…",
  "Choisissez un client": "Select a client",
  "Client non renseigné": "No client set",
  "Dépannage chaudière…": "Boiler emergency repair…",
  "En retard — échéance": "Overdue — due date",
  "Enregistrer le devis": "Save quote",
  "Envoi de la relance…": "Sending chase…",
  "Fournisseur supprimé": "Supplier deleted",
  "Matériaux, matériel…": "Materials, equipment…",
  "Modifier le chantier": "Edit job site",
  "Modifier le matériel": "Edit equipment",
  "Modifier le pointage": "Edit time entry",
  "Négoce / fournisseur": "Merchant / supplier",
  "Nom du fournisseur :": "Supplier name:",
  "Nouvelle opportunité": "New opportunity",
  "Prestation supprimée": "Service deleted",
  "Prix de vente (€ HT)": "Sale price (€ excl. VAT)",
  "Santé d'encaissement": "Collection health",
  "Suivi de rentabilité": "Profitability tracking",
  "Voir les partenaires": "View partners",
  "— Aucun (interne) —": "— None (internal) —",
  "+ Ajouter un client": "+ Add a client",
  "+ Nouvel équipement": "+ New equipment",
  "➕ Nouveau chantier…": "➕ New job site…",
  "À renouveler (30 j)": "To renew (30 d)",
  "Affectation retirée": "Assignment removed",
  "Affecter une équipe": "Assign a team",
  "Aucune intervention": "No jobs",
  "Budget prévisionnel": "Planned budget",
  "Budget prévu (€ HT)": "Planned budget (€ excl. VAT)",
  "Chantier enregistré": "Job site saved",
  "Charge par équipier": "Workload per team member",
  "Chaufferie, garage…": "Boiler room, garage…",
  "contact & assurance": "contact & insurance",
  "Contrat d'entretien": "Servicing contract",
  "Décennale manquante": "Missing 10-year insurance",
  "Devis émis par mois": "Quotes issued per month",
  "Entretien à prévoir": "Servicing due",
  "Entretien en retard": "Servicing overdue",
  "Entretien récurrent": "Recurring servicing",
  "Équipement supprimé": "Equipment deleted",
  "Équipier enregistré": "Team member saved",
  "équipiers planifiés": "team members scheduled",
  "Facture enregistrée": "Invoice saved",
  "Heures par chantier": "Hours per job site",
  "Maçon, électricien…": "Mason, electrician…",
  "Matériel enregistré": "Equipment saved",
  "Modifier l'équipier": "Edit team member",
  "Modifier la facture": "Edit invoice",
  "Modifier le contrat": "Edit contract",
  "Nom de l'équipier :": "Team member name:",
  "Nouveau fournisseur": "New supplier",
  "Nouvelle prestation": "New service",
  "Partenaire supprimé": "Partner deleted",
  "Pointage des heures": "Time tracking",
  "Pointage enregistré": "Time entry saved",
  "Prix d'achat HT (€)": "Cost price excl. VAT (€)",
  "Prochaine visite le": "Next visit on",
  "Réapprovisionnement": "Restocking",
  "Relance en retard (": "Chase overdue (",
  "Supprimer le client": "Delete client",
  "Terminées (7 jours)": "Completed (7 days)",
  "Vérifier les lignes": "Check the line items",
  "— Aucun chantier —": "— No job site —",
  ".\n\nMerci d'avance,": ".\n\nThanks in advance,",
  "+ Nouveau chantier": "+ New job site",
  "+ Nouvelle facture": "+ New invoice",
  "+ Saisir à la main": "+ Enter manually",
  "➕ Nouvel équipier…": "➕ New team member…",
  "à réapprovisionner": "to restock",
  "Ajouter l'équipier": "Add team member",
  "Article enregistré": "Item saved",
  "Budget du chantier": "Job site budget",
  "Chantiers en cours": "Ongoing job sites",
  "Choisissez un jour": "Pick a day",
  "Commande envoyée à": "Order sent to",
  "Contrat enregistré": "Contract saved",
  "Devis / diagnostic": "Quote / diagnosis",
  "Encaisser le solde": "Collect balance",
  "Entonnoir de vente": "Sales funnel",
  "Équipement couvert": "Equipment covered",
  "équipements suivis": "equipment tracked",
  "expire aujourd'hui": "expires today",
  "Fournisseur ajouté": "Supplier added",
  "Heures de l'équipe": "Team hours",
  "Intervention créée": "Job created",
  "Modifier l'article": "Edit item",
  "Modifier le client": "Edit client",
  "Montant estimé (€)": "Estimated amount (€)",
  "Nouveau partenaire": "New partner",
  "Pilotez votre cash": "Manage your cash",
  "Pointer des heures": "Log hours",
  "Prestation ajoutée": "Service added",
  "Prochain entretien": "Next servicing",
  "Prochaine visite ·": "Next visit ·",
  "Semaine précédente": "Previous week",
  "Suivi de chantiers": "Job site tracking",
  "Supprimer la ligne": "Delete line",
  "Tableau électrique": "Electrical panel",
  "Taux d'acceptation": "Acceptance rate",
  "Tous les clients →": "All clients →",
  "Tout enregistrer (": "Save all (",
  "Type de partenaire": "Partner type",
  "u, m², h, forfait…": "u, m², h, flat rate…",
  "Validation retirée": "Approval removed",
  "Visite de contrôle": "Technical visit",
  ";border:1px solid": ";border:1px solid",
  "+ Nouveau contrat": "+ New contract",
  "+ Nouvel équipier": "+ New team member",
  "➕ Nouveau client…": "➕ New client…",
  "Action impossible": "Action not possible",
  "Ajouté à l'équipe": "Added to team",
  "Ajouter le client": "Add client",
  "Aller à la saisie": "Go to entry",
  "Assurance expirée": "Insurance expired",
  "Aucun fournisseur": "No supplier",
  "Budget enregistré": "Budget saved",
  "Catalogue de prix": "Price list",
  "Chantier supprimé": "Job site deleted",
  "Client à préciser": "Client to specify",
  "Client enregistré": "Client saved",
  "client@exemple.fr": "client@example.com",
  "Copilote planning": "Schedule copilot",
  "Créer le chantier": "Create job site",
  "Dernier entretien": "Last servicing",
  "Encaissé par mois": "Collected per month",
  "Équipement ajouté": "Equipment added",
  "Facture non créée": "Invoice not created",
  "Facture supprimée": "Invoice deleted",
  "Facturer le solde": "Invoice balance",
  "garantie jusqu'au": "warranty until",
  "h de main d'œuvre": "h of labor",
  "Matériel supprimé": "Equipment deleted",
  "Modifier la tâche": "Edit task",
  "Modifier le devis": "Edit quote",
  "Nom du chantier :": "Job site name:",
  "Nom du chantier *": "Job site name *",
  "Note (facultatif)": "Note (optional)",
  "Nouvel équipement": "New equipment",
  "Opportunité créée": "Opportunity created",
  "Partenaire ajouté": "Partner added",
  "Planning chantier": "Job site schedule",
  "Pointage supprimé": "Time entry deleted",
  "Pointages du jour": "Today's time entries",
  "Quantité en stock": "Quantity in stock",
  "Relance envoyée à": "Chase sent to",
  "reste à encaisser": "left to collect",
  "SAV & maintenance": "After-sales & maintenance",
  "SAV sous garantie": "After-sales (warranty)",
  "Statut mis à jour": "Status updated",
  "Tâche enregistrée": "Task saved",
  "Tâche, précision…": "Task, details…",
  "Type d'équipement": "Equipment type",
  "— Aucun client —": "— No client —",
  "— Non assignée —": "— Unassigned —",
  "+ Nouveau client": "+ New client",
  "+ Nouvel article": "+ New item",
  "+ Nouvelle tâche": "+ New task",
  "Ajuster le stock": "Adjust stock",
  "Article supprimé": "Item deleted",
  "Aucun équipement": "No equipment",
  "Aucun partenaire": "No partner",
  "Avancement moyen": "Average progress",
  "Chantier affecté": "Job site assigned",
  "chantiers actifs": "active job sites",
  "Chantiers actifs": "Active job sites",
  "Chef de chantier": "Site manager",
  "Contrat supprimé": "Contract deleted",
  "Créer la facture": "Create invoice",
  "devis enregistré": "quote saved",
  "Devis enregistré": "Quote saved",
  "Entretien annuel": "Annual servicing",
  "Envoi impossible": "Send failed",
  "Équipes & tâches": "Teams & tasks",
  "Facture soldée ·": "Invoice settled ·",
  "Fournisseur créé": "Supplier created",
  "Nouveau chantier": "New job site",
  "Nouveau matériel": "New equipment",
  "Nouvelle facture": "New invoice",
  "opacity .6s ease": "opacity .6s ease",
  "Paiement partiel": "Partial payment",
  "Prochaine action": "Next action",
  "Prochaine visite": "Next visit",
  "Réf. fournisseur": "Supplier ref.",
  "Rien à commander": "Nothing to order",
  "Sans fournisseur": "No supplier",
  "Semaine suivante": "Next week",
  "Seuil d'alerte :": "Alert threshold:",
  "Suivi commercial": "Sales tracking",
  "Tâche terminée ✓": "Task done ✓",
  "TTC (échéance le": "incl. VAT (due",
  "Valable jusqu'au": "Valid until",
  "Valider ce devis": "Accept this quote",
  "Voir le pipeline": "View pipeline",
  "— Non affecté —": "— Unassigned —",
  "+ Nouveau devis": "+ New quote",
  "Aucune échéance": "No due dates",
  "Autres contrats": "Other contracts",
  "Charge actuelle": "Current workload",
  "Client supprimé": "Client deleted",
  "contrats actifs": "active contracts",
  "Corps de métier": "Trade",
  "créés récemment": "created recently",
  "d'un montant de": "in the amount of",
  "Date de facture": "Invoice date",
  "Dicter un devis": "Dictate a quote",
  "Enregistrement…": "Saving…",
  "Équipier ajouté": "Team member added",
  "Équipier retiré": "Team member removed",
  "Fin de garantie": "Warranty ends",
  "h cette semaine": "h this week",
  "Heures pointées": "Hours tracked",
  "jours planifiés": "days scheduled",
  "Matériel ajouté": "Equipment added",
  "Mise en service": "Commissioning",
  "Nom du client :": "Client name:",
  "Nouveau contrat": "New contract",
  "Nouvel équipier": "New team member",
  "Pointage validé": "Time entry approved",
  "Pompe à chaleur": "Heat pump",
  "Prix d'achat HT": "Cost excl. VAT",
  "Relance facture": "Invoice chase",
  "réponse tardive": "late reply",
  "Rien à relancer": "Nothing to chase",
  "Semaine prête ·": "Week ready ·",
  "Silence relance": "Silent, chase up",
  "Tableau de bord": "Dashboard",
  "Tâche supprimée": "Task deleted",
  "Tâches en cours": "Tasks in progress",
  "tout est à jour": "all up to date",
  "Tout est à jour": "All up to date",
  "Valeur du stock": "Stock value",
  "Valeur en stock": "Value in stock",
  ";border-color:": ";border-color:",
  "+ Intervention": "+ Job",
  "6 mois à venir": "Next 6 months",
  "Article ajouté": "Item added",
  "Aucun chantier": "No job sites",
  "Aucun équipier": "No team members",
  "Aucun matériel": "No equipment",
  "Aucune facture": "No invoices",
  "AXA n°DC-88213": "AXA #DC-88213",
  "Catalogue vide": "Price list empty",
  "Chef d'équipe…": "Foreman…",
  "Créer la tâche": "Create task",
  "Créer le devis": "Create quote",
  "Devis envoyé à": "Quote sent to",
  "Devis supprimé": "Quote deleted",
  "devis tranchés": "quotes decided",
  "Jour précédent": "Previous day",
  "Mon entreprise": "My company",
  "Montant HT (€)": "Amount excl. VAT (€)",
  "Notes internes": "Internal notes",
  "Nouveau client": "New client",
  "Nouvel article": "New item",
  "Nouvelle tâche": "New task",
  "Pipeline actif": "Active pipeline",
  "Rien à piloter": "Nothing to track",
  "Rien à traiter": "Nothing to handle",
  "Sans catégorie": "Uncategorized",
  "Saunier Duval…": "Saunier Duval…",
  "Seuil d'alerte": "Alert threshold",
  "Sous-traitants": "Subcontractors",
  "Stock & achats": "Stock & purchases",
  "sur 8 semaines": "over 8 weeks",
  "Tâche déplacée": "Task moved",
  "tâches actives": "active tasks",
  "Total ligne HT": "Line total excl. VAT",
  "Toute l'équipe": "Whole team",
  "· aujourd'hui": "· today",
  "· réalisée le": "· completed on",
  "%;background:": "%;background:",
  "+ Fournisseur": "+ Supplier",
  "+ Opportunité": "+ Opportunity",
  "Aucun article": "No items",
  "Aucun contrat": "No contracts",
  "aujourd'hui ·": "today ·",
  "Budget (€ HT)": "Budget (€ excl. VAT)",
  "Budget engagé": "Budget committed",
  "cette semaine": "this week",
  "Cette semaine": "This week",
  "Chantier créé": "Job site created",
  "Client ajouté": "Client added",
  "Climatisation": "Air conditioning",
  "color:#E11D48": "color:#E11D48",
  "Date du devis": "Quote date",
  "Désignation *": "Description *",
  "Devis ce mois": "Quotes this month",
  "Devis récents": "Recent quotes",
  "devis reconnu": "quote recognized",
  "Devis vérifié": "Quote checked",
  "Disponibilité": "Availability",
  "Échéance dans": "Due in",
  "Engagé (€ HT)": "Committed (€ excl. VAT)",
  "Engin, outil…": "Machine, tool…",
  "entrée dont l": "entry whose",
  "expiré depuis": "expired for",
  "Facture créée": "Invoice created",
  "Interventions": "Jobs",
  "jour planifié": "day scheduled",
  "Non conformes": "Non-compliant",
  "Non planifiée": "Not scheduled",
  "Non planifiés": "Not scheduled",
  "Nouveau devis": "New quote",
  "Parc installé": "Installed base",
  "Quincaillerie": "Hardware",
  "Récap semaine": "Week recap",
  "Récapitulatif": "Summary",
  "rien d'urgent": "nothing urgent",
  "Sans chantier": "No job site",
  "Sous 30 jours": "Within 30 days",
  "Sous garantie": "Under warranty",
  "Sous-traitant": "Subcontractor",
  "Tableau élec.": "Elec. panel",
  "Voir le stock": "View stock",
  "(prestation)": "(service)",
  "% des heures": "% of hours",
  "+ Équipement": "+ Equipment",
  "+ Prestation": "+ Service",
  "À renouveler": "To renew",
  "Acompte 30 %": "30% deposit",
  "Aucun client": "No clients",
  "Aucune tâche": "No tasks",
  "Budget prévu": "Planned budget",
  "Collectivité": "Public sector",
  "Contrat créé": "Contract created",
  "CTR-2026-014": "CTR-2026-014",
  "Date de pose": "Install date",
  "Déjà facturé": "Already invoiced",
  "Devis dictés": "Dictated quotes",
  "devis envoyé": "quote sent",
  "Devis envoyé": "Quote sent",
  "En retard de": "Overdue by",
  "Encaissement": "Collection",
  "Fournisseurs": "Suppliers",
  "gagné · 30 j": "won · 30 d",
  "h pointées ·": "h tracked ·",
  "Hors service": "Out of service",
  "Informations": "Information",
  "Intervention": "Job",
  "Jour suivant": "Next day",
  "Localisation": "Location",
  "Main d'œuvre": "Labor",
  "Marge prévue": "Planned margin",
  "Marge réelle": "Actual margin",
  "non assignée": "unassigned",
  "Non assignée": "Unassigned",
  "non planifié": "not scheduled",
  "œuvre) ── */": "œuvre) ── */",
  "Opportunités": "Opportunities",
  "réceptionnés": "handed over",
  "représentent": "represent",
  "Terminées 7j": "Done 7d",
  "votre projet": "your project",
  "Votre projet": "Your project",
  "· entretien": "· servicing",
  "· matériaux": "· materials",
  "· PDF joint": "· PDF attached",
  "(en retard)": "(overdue)",
  "à commander": "to order",
  "À encaisser": "To collect",
  "À planifier": "To schedule",
  "Aucun devis": "No quotes",
  "aujourd'hui": "today",
  "Aujourd'hui": "Today",
  "background:": "background:",
  "Chauffe-eau": "Water heater",
  "Client créé": "Client created",
  "Code postal": "ZIP code",
  "Coûts réels": "Actual costs",
  "Date prévue": "Planned date",
  "Description": "Description",
  "électricité": "electrical",
  "Électricité": "Electrical",
  "en retard ·": "overdue ·",
  "Enregistrer": "Save",
  "Équipements": "Equipment",
  "expire dans": "expires in",
  "Facturation": "Invoicing",
  "Fournisseur": "Supplier",
  "go('stock')": "go('stock')",
  "gros oeuvre": "structural work",
  "Intervenant": "Technician",
  "j de retard": "d overdue",
  "Jour libéré": "Day freed",
  "Maintenance": "Maintenance",
  "Montant (€)": "Amount (€)",
  "N° de série": "Serial no.",
  "Non affecté": "Unassigned",
  "opportunité": "opportunity",
  "Opportunité": "Opportunity",
  "Partenaires": "Partners",
  "Particulier": "Individual",
  "Périodicité": "Frequency",
  "Proposition": "Proposal",
  "Répartition": "Breakdown",
  "Tâche créée": "Task created",
  "Trimestriel": "Quarterly",
  "· échéance": "· due",
  "% du prévu": "% of plan",
  "+ Affecter": "+ Assign",
  "+ Chantier": "+ Job site",
  "+ Équipier": "+ Team member",
  "+ Facturer": "+ Invoice",
  "+ Matériel": "+ Equipment",
  "➕ Nouveau…": "➕ New…",
  "à échéance": "due",
  "à relancer": "to chase up",
  "À relancer": "To chase up",
  "Assignée à": "Assigned to",
  "Avancement": "Progress",
  "Brouillons": "Drafts",
  "catégories": "categories",
  "Conditions": "Terms",
  "Conformité": "Compliance",
  "Devis créé": "Quote created",
  "Disponible": "Available",
  "en attente": "pending",
  "En attente": "Pending",
  "en cours ·": "in progress ·",
  "en rupture": "out of stock",
  "Entreprise": "Company",
  "équipement": "equipment",
  "Équipement": "Equipment",
  "Équipier *": "Team member *",
  "Fin prévue": "Planned end",
  "Fourniture": "Materials",
  "gros œuvre": "structural work",
  "Gros œuvre": "Structural",
  "h au total": "h total",
  "Intitulé *": "Title *",
  "maçonnerie": "masonry",
  "Menuiserie": "Joinery",
  "Montant HT": "Amount excl. VAT",
  "Partenaire": "Partner",
  "Prestation": "Service",
  "références": "items",
  "semaine du": "week of",
  "Semaine du": "Week of",
  "Semestriel": "Half-yearly",
  "Spécialité": "Trade",
  "sur 6 mois": "over 6 months",
  "ThemaPlus…": "ThemaPlus…",
  "Trésorerie": "Cash flow",
  "— Aucun —": "— None —",
  "/ facturé": "/ invoiced",
  "% accepté": "% accepted",
  "+ Ajouter": "+ Add",
  "+ Article": "+ Item",
  "+ Contrat": "+ Contract",
  "+ Facture": "+ Invoice",
  "+ Nouveau": "+ New",
  "+ Pointer": "+ Log time",
  "➕ Créer «": "➕ Create '",
  "1A;color:": "1A;color:",
  "30 à 60 j": "30 to 60 d",
  "60 à 90 j": "60 to 90 d",
  "90 j et +": "90 d and +",
  "à fournir": "to provide",
  "à traiter": "to handle",
  "À traiter": "To handle",
  "à valider": "to approve",
  "Brouillon": "Draft",
  "Carrelage": "Tiling",
  "Catalogue": "Price list",
  "Catégorie": "Category",
  "Chantiers": "Job sites",
  "Chaudière": "Boiler",
  "Commander": "Order",
  "Conformes": "Compliant",
  "Continuer": "Continue",
  "Coût réel": "Actual cost",
  "Décennale": "10-year liability",
  "Dépannage": "Emergency repair",
  "Dicté : «": "Dictated: '",
  "Durée (h)": "Duration (h)",
  "Échéances": "Due dates",
  "en retard": "overdue",
  "En retard": "Overdue",
  "Entretien": "Servicing",
  "Expire le": "Expires on",
  "Expiré le": "Expired on",
  "Heure sup": "Overtime",
  "hui ── */": "hui ── */",
  "Isolation": "Insulation",
  "Outillage": "Tooling",
  "Partielle": "Partial",
  "Planifiée": "Scheduled",
  "Plomberie": "Plumbing",
  "Plus tard": "Later",
  "Prévue le": "Planned for",
  "référence": "item",
  "Référence": "Reference",
  "Situation": "Progress invoice",
  "sous 30 j": "within 30 d",
  "Stock bas": "Low stock",
  "Supprimer": "Delete",
  "Téléphone": "Phone",
  "Terminées": "Completed",
  "Total TTC": "Total incl. VAT",
  "Tout voir": "View all",
  "· soldée": "· paid",
  "+ Client": "+ Client",
  "0 à 30 j": "0 to 30 d",
  "60 jours": "60 days",
  "À jour ✓": "Up to date ✓",
  "À suivre": "To follow up",
  "Acceptés": "Accepted",
  "Affecter": "Assign",
  "Articles": "Items",
  "Chantier": "Job site",
  "Client *": "Client *",
  "Conforme": "Compliant",
  "Contacté": "Contacted",
  "Contrats": "Contracts",
  "Démarrer": "Start",
  "Détail (": "Details (",
  "Dimanche": "Sunday",
  "Échéance": "Due date",
  "email. C": "email. C",
  "En arrêt": "On leave",
  "en cours": "in progress",
  "En cours": "In progress",
  "en stock": "in stock",
  "En stock": "In stock",
  "Encaissé": "Collected",
  "équipier": "team member",
  "Équipier": "Team member",
  "Escalade": "Escalation",
  "Expirées": "Expired",
  "Factures": "Invoices",
  "Garantie": "Warranty",
  "identité": "identity",
  "Installé": "Installed",
  "Matériel": "Equipment",
  "Mercredi": "Wednesday",
  "Modifier": "Edit",
  "par mois": "per month",
  "Peinture": "Paint",
  "Pilotage": "Overview",
  "Pipeline": "Pipeline",
  "Planning": "Schedule",
  "Priorité": "Priority",
  "Quantité": "Quantity",
  "Relancer": "Chase up",
  "Sans ch.": "No site",
  "Sans nom": "Untitled",
  "Soldée ✓": "Paid ✓",
  "Suspendu": "Suspended",
  "terminée": "completed",
  "Terminée": "Completed",
  "Terminer": "Complete",
  "Terminés": "Completed",
  "Total HT": "Total excl. VAT",
  "Vendredi": "Friday",
  "— suivi": "— tracking",
  ";color:": ";color:",
  "· reste": "· remaining",
  "· seuil": "· threshold",
  "% · fin": "% · end",
  "+ Ligne": "+ Line",
  "+ Tâche": "+ Task",
  "À faire": "To do",
  "À venir": "Upcoming",
  "Absence": "Absence",
  "Accepté": "Accepted",
  "Acompte": "Deposit",
  "Adresse": "Address",
  "Affecté": "Assigned",
  "Ajouter": "Add",
  "Annulée": "Canceled",
  "Annuler": "Cancel",
  "Article": "Item",
  "Budgets": "Budgets",
  "ce jour": "today",
  "Clients": "Clients",
  "Contact": "Contact",
  "Contrat": "Contract",
  "créée ·": "created ·",
  "dépassé": "exceeded",
  "engagés": "committed",
  "Envoyée": "Sent",
  "Envoyer": "Send",
  "Envoyés": "Sent",
  "ex : 10": "e.g. 10",
  "expirés": "expired",
  "Expirés": "Expired",
  "Facture": "Invoice",
  "Facturé": "Invoiced",
  "Finance": "Finance",
  "Inactif": "Inactive",
  "Mensuel": "Monthly",
  "Montant": "Amount",
  "Normale": "Normal",
  "Nouveau": "New",
  "Ouvrage": "Work item",
  "Pointer": "Clock in",
  "Posé le": "Installed",
  "Pour le": "For",
  "Rapport": "Report",
  "Réappro": "Restock",
  "Refusés": "Declined",
  "Résilié": "Terminated",
  "Retirer": "Remove",
  "Rupture": "Out of stock",
  "Suivant": "Next",
  "sur 2 ·": "of 2 ·",
  "Terminé": "Completed",
  "Valider": "Approve",
  "Annuel": "Yearly",
  "Annulé": "Canceled",
  "aucune": "none",
  "Autres": "Other",
  "Budget": "Budget",
  "Client": "Client",
  "Détail": "Details",
  "Dicter": "Dictate",
  "dirigé": "led",
  "Engagé": "Committed",
  "envoyé": "sent",
  "Envoyé": "Sent",
  "Équipe": "Team",
  "Expiré": "Expired",
  "Heures": "Hours",
  "Maçon…": "Mason…",
  "Marque": "Brand",
  "Modèle": "Model",
  "Normal": "Normal",
  "Payées": "Paid",
  "Prénom": "First name",
  "Refusé": "Declined",
  "Retard": "Overdue",
  "Retour": "Back",
  "Saisie": "Entry",
  "Samedi": "Saturday",
  "Simple": "Simple",
  "Source": "Source",
  "Statut": "Status",
  "Tâches": "Tasks",
  "Toutes": "All",
  "Trajet": "Travel",
  "validé": "approved",
  "Validé": "Approved",
  "· TVA": "· VAT",
  "(réf.": "(ref.",
  "Actif": "Active",
  "Aucun": "None",
  "Autre": "Other",
  "Avoir": "Credit note",
  "Basse": "Low",
  "boîte": "box",
  "Créer": "Create",
  "Début": "Start",
  "Devis": "Quote",
  "Durée": "Duration",
  "Étape": "Step",
  "févr.": "Feb",
  "gagné": "won",
  "Gagné": "Won",
  "h sup": "h overtime",
  "Haute": "High",
  "janv.": "Jan",
  "Jeudi": "Thursday",
  "juil.": "Jul",
  "Lundi": "Monday",
  "Mardi": "Tuesday",
  "Mens.": "Mo.",
  "Moins": "Less",
  "Nom *": "Name *",
  "Notes": "Notes",
  "Payée": "Paid",
  "Perdu": "Lost",
  "pers.": "ppl.",
  "Placo": "Plasterboard",
  "PU HT": "Unit price",
  "Récap": "Summary",
  "Reste": "Remaining",
  "sept.": "Sep",
  "signé": "signed",
  "Stock": "Stock",
  "sur 3": "of 3",
  "tâche": "task",
  "Tâche": "Task",
  "Trim.": "Qtr.",
  "Unité": "Unit",
  "Ville": "City",
  "abs.": "abs.",
  "Ann.": "Yr.",
  "août": "Aug",
  "auj.": "today",
  "avr.": "Apr",
  "Clim": "HVAC",
  "dans": "in",
  "déc.": "Dec",
  "éch.": "due",
  "Éch.": "Due",
  "Jour": "Day",
  "juin": "Jun",
  "mars": "Mar",
  "nov.": "Nov",
  "oct.": "Oct",
  "Plus": "More",
  "Rôle": "Role",
  "Sem.": "Wk.",
  "Tous": "All",
  "Type": "Type",
  "dim": "sun",
  "Fin": "End",
  "j —": "d —",
  "j ·": "d ·",
  "jeu": "thu",
  "lun": "mon",
  "mai": "May",
  "mar": "tue",
  "mer": "wed",
  "Qté": "Qty",
  "sam": "sat",
  "sur": "of",
  "Sur": "Of",
  "ven": "fri",
  "D-": "D-",
  "F-": "F-",
};
